### PR TITLE
Add Traditional Chinese translation

### PR DESCRIPTION
**Pull request by SiderealArt**

### CODE REVIEW

**Comment by or-else** [comment]
Thanks. There are more strings to translate though:
https://github.com/tinode/ios/tree/devel/Tinodios/zh-Hans.lproj

**Comment by SiderealArt** [comment]
> 
> 
> Thanks. There are more strings to translate though:
> https://github.com/tinode/ios/tree/devel/Tinodios/zh-Hans.lproj

I am not quite familiar with the wording of Simplified Chinese. So I might not be able to help. sorry!

**Comment by or-else** [comment]
There is also English and Spanish there:
https://github.com/tinode/ios/tree/master/Tinodios

**Comment by SiderealArt** [comment]
> 
> 
> There is also English and Spanish there:
> https://github.com/tinode/ios/tree/devel/Tinodios

Done!

**Comment by or-else** [comment]
Great, thanks.

**Pull request merged**
